name: github_rest_api
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.3
  dotenv: ^3.0.0
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test: ^1.15.0
  test_process: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

assets:
  - .env